spring:
  redis:
    host: ${REDIS_HOST:47.94.11.22}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:123456}
    database: 12
    lettuce:
      pool:
        max-active: 300
  datasource:
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:118.178.132.240}:${DATASOURCE_PORT:3306}/nacos?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: 346789051